---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'release/') }}
    uses: networkservicemesh/.github/.github/workflows/release.yaml@main
    with:
      dependent_repositories: |
        ["cmd-forwarder-sriov",
        "cmd-nsc",
        "cmd-nsc-init",
        "cmd-nse-icmp-responder",
        "cmd-forwarder-vpp",
        "cmd-nse-vlan-vpp",
        "sdk-ovs"]

    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}