---
name: Update dependent repositories
on:
  push:
    branches:
      - main
  workflow_run:
    types:
      - completed
    workflows:
      - 'automerge'
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' || github.event_name == 'push' }}
    uses: networkservicemesh/.github/.github/workflows/update-dependent-repositories-gomod.yaml@main
    with:
      dependent_repositories: |
        ["cmd-forwarder-sriov",
        "cmd-nsc",
        "cmd-nsc-init",
        "cmd-nse-icmp-responder",
        "cmd-forwarder-vpp",
        "cmd-nse-vlan-vpp",
        "sdk-ovs"]
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}